<?php

/**
 * @file
 * Single Sign On extended features for Drupal 7 websites.
 */

/**
 * Implements hook_form_alter().
 */
function cognito_sso_form_alter(array &$form, array &$form_state, $form_id) {

  // Adding a Role sync field to openid_connect config form.
  if ($form_id == 'openid_connect_admin_form') {
    $form['user_role_sync'] = array(
      '#title' => t('Role sync'),
      '#type' => 'fieldset',
    );

    $form['user_role_sync']['openid_connect_enable_role_sync'] = array(
      '#title' => t('Enable Role sync'),
      '#description' => t('Enabling this will send the user role data to the IDP.'),
      '#type' => 'checkbox',
      '#default_value' => variable_get('openid_connect_enable_role_sync', TRUE),
    );

    // Additional submit handler for openid connect value.
    $form['actions']['submit']['#submit'][] = 'cognito_sso_openid_connect_admin_form_submit';
  }
}

/**
 * Additional submit handler for openid connect value.
 */
function cognito_sso_openid_connect_admin_form_submit(&$form, &$form_state) {
  if (isset($form_state['values']['user_role_sync']['openid_connect_enable_role_sync'])) {
    variable_set('openid_connect_enable_role_sync', $form_state['values']['user_role_sync']['openid_connect_enable_role_sync']);
  }
}
